### PR TITLE
fix: allow object for overriding private key when signing

### PR DESCRIPTION
**Pull request by 39hn-zz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

It must be able to pass an object `{ key, passphrase }` as privateKey for RSA and ECDSA algorithm.
It's possible on module option but not on overriding private key when signing.

## What is the new behavior?
Fix privateKey type to allow to pass object for overriding private key when signing

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by micalevisk** [comment]
could you please change the line below from `npm@latest` to `npm@^8` to fix the pipeline

https://github.com/nestjs/jwt/blob/ef435fb0686daf8806729e71dffa4abe01b4d123/.circleci/config.yml#L25

**Comment by 39hn** [comment]
> could you please change the line below from `npm@latest` to `npm@^8` to fix the pipeline
> 
> https://github.com/nestjs/jwt/blob/ef435fb0686daf8806729e71dffa4abe01b4d123/.circleci/config.yml#L25

sure!!

**Review by thenglong — APPROVED** [review]

**Comment by david-a** [comment]
Hi, I haven't noticed your PR and opened a similar one, but with tests and no other changes (e.g. config.yml)
https://github.com/nestjs/jwt/pull/1192

**Comment by kamilmysliwiec** [comment]
lgtm

**Pull request merged**
