### PR TITLE
fix: update jwt module to use module options builder

### LINKED ISSUE #1064: jwt module shoud  extends ConfigurableModuleClass
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

JwtModule does not use the nestjs v9 ModuleOptionsBuilder. That said we cannot use the providers from the parent module when we want to pass the options from a parent module (as describe here: nestjs/nest#9935).

### Minimum reproduction code

https://github.com/nestjs/nest/pull/9935

### Steps to reproduce

Try to use this kind of configuration described in the merged pull request.

```ts
         JwtModule.registerAsync({
          useFactory(opt: AuthenticationOptions) {
            return opt.jwtOptions;
          },
          inject: [AuthenticationOptions],
        }),
```

When using this code we cannot inject `JwtService` in our service from our parent module

### Expected behavior

Allow `provideInjectionTokensFrom` to be able to use the config providers from a parent module 

### Package version

9.0.0

### NestJS version

9.0.11

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

_No response_

### PR DESCRIPTION
**Pull request by floross**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Fix #1064

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by micalevisk — CHANGES_REQUESTED** [review]
please revert the changes made on `package.json` file

**Comment by floross** [comment]
> please revert the changes made on `package.json` file

It should be good now, I revert the `package.json` and `package-lock.json`

**Comment by floross** [comment]
Do you have any update on when we could merge this pr into master?

**Comment by allanvobraun** [comment]
Any updates on this PR?

**Comment by milo526** [comment]
@kamilmysliwiec This feature would be very useful to us, is there anything we can do to help this getting merged?

**Comment by kamilmysliwiec** [comment]
This change shouldn't have any impact on the behavior of the module.

**Pull request closed without merging**
